import Head from "next/head";
import styles from "../styles/Home.module.css";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="/homeimg.jpg"
            width={259}
            height={173}
            alt="hunting coder"
          />
        </div>
        <h1 className={styles.title}>&lt;Hunting Coder/&gt;</h1>
        <div className={styles.blogs}>
          <h2>Latest Blog&apos;s</h2>
          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>JavaScript is the language used to design Logic for the Web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>JavaScript is the language used to design Logic for the Web</p>
            <button className={styles.btn}>Read More</button>

          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>JavaScript is the language used to design Logic for the Web</p>
            <button className={styles.btn}>Read More</button>

          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
