import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size: 38px;
        }
        h3{
          font-size: 28px;
        }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}

      
      <main className={styles.main}>
        
        <h1 className={styles.title}>
        Hunting Coder
        </h1>
        <div className={styles.imagewrap}>

        <Image className={styles.myImg} src="/homeimg.jpg" width={259} height={173}/>
        </div>

        <p className={styles.description}>
         A Blog for Hunting Coders by a Hunting Coder
        </p>

        <div className={styles.blogs}>
          <h2>Latest Blog's</h2>
          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>JavaScript is the language used to design Logic for the Web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>JavaScript is the language used to design Logic for the Web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>JavaScript is the language used to design Logic for the Web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
